I'm done
SpriteSpirit/java-objects-constructors pull request #1
Opened 2023-08-25 14:51 UTC by SpriteSpirit

2023-08-25 20:01 UTC, isavinov requested changes

2023-08-25 20:01 UTC, isavinov commented on Theory/src/Book_.java
> +    String authorName;
Все что в этом пакете я могу игнорировать?

2023-08-25 20:01 UTC, isavinov commented on src/Book.java
> +    private String author;
author должен быть типа Author, а не String
`private Author author`

2023-08-25 20:46 UTC, SpriteSpirit commented on Theory/src/Book_.java
> +    String authorName;
Да, этот пакет для теории из урока (неудобно создавать десятки проектов)

2023-08-25 20:46 UTC, SpriteSpirit commented on src/Book.java
> +    private String author;
"Понял-принял".
Код поправила

2023-08-26 10:17 UTC, isavinov approved these changes

2023-08-26 10:17 UTC, isavinov commented on src/Author.java
> +    public String fullName() {
только getFullName. Метод это действие, желательно глаголы использовать

2024-10-20 18:51 UTC, merged